//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Almotkaml.HR.EntityCore.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Names {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Names() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Almotkaml.HR.EntityCore.Resource.Names", typeof(Names).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مسجون.
        /// </summary>
        public static string Jailed {
            get {
                return ResourceManager.GetString("Jailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نفقة شرعية.
        /// </summary>
        public static string Legal {
            get {
                return ResourceManager.GetString("Legal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مستمر.
        /// </summary>
        public static string Mostmer {
            get {
                return ResourceManager.GetString("Mostmer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مركز سبها.
        /// </summary>
        public static string SabhaCenter {
            get {
                return ResourceManager.GetString("SabhaCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إصابة عمل.
        /// </summary>
        public static string sickleave {
            get {
                return ResourceManager.GetString("sickleave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موقوف.
        /// </summary>
        public static string Stopsalary {
            get {
                return ResourceManager.GetString("Stopsalary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مركز طبرق.
        /// </summary>
        public static string TobreqCenter {
            get {
                return ResourceManager.GetString("TobreqCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مركز طرابلس.
        /// </summary>
        public static string TripoliCenter {
            get {
                return ResourceManager.GetString("TripoliCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إجازة الحج.
        /// </summary>
        public static string Vacationalhaju {
            get {
                return ResourceManager.GetString("Vacationalhaju", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اجازة طارئة.
        /// </summary>
        public static string VacationEmergency {
            get {
                return ResourceManager.GetString("VacationEmergency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إجازة الزواج.
        /// </summary>
        public static string Vacationmarriage {
            get {
                return ResourceManager.GetString("Vacationmarriage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إجازة الامومة.
        /// </summary>
        public static string Vacationmaternityleave {
            get {
                return ResourceManager.GetString("Vacationmaternityleave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اجازة مرضية.
        /// </summary>
        public static string VacationSick {
            get {
                return ResourceManager.GetString("VacationSick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اجازة بدون مرتب.
        /// </summary>
        public static string VacationWithoutPay {
            get {
                return ResourceManager.GetString("VacationWithoutPay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اجازة سنوية.
        /// </summary>
        public static string VacationYear {
            get {
                return ResourceManager.GetString("VacationYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مركز الزاوية.
        /// </summary>
        public static string ZawiaCenter {
            get {
                return ResourceManager.GetString("ZawiaCenter", resourceCulture);
            }
        }
    }
}
