//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Almotkaml.HR.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Titles {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Titles() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Almotkaml.HR.Resources.Titles", typeof(Titles).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الدليل المحاسبي.
        /// </summary>
        public static string AccountingManuals {
            get {
                return ResourceManager.GetString("AccountingManuals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قيود الاستحقاق.
        /// </summary>
        public static string AccuralEntries {
            get {
                return ResourceManager.GetString("AccuralEntries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نسخ.
        /// </summary>
        public static string BackUp {
            get {
                return ResourceManager.GetString("BackUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التسويات المصرفية.
        /// </summary>
        public static string BankReconciliations {
            get {
                return ResourceManager.GetString("BankReconciliations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أذونات الصرف بالصكوك.
        /// </summary>
        public static string BillBonds {
            get {
                return ResourceManager.GetString("BillBonds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أذونات الصرف النقدية.
        /// </summary>
        public static string BillCashes {
            get {
                return ResourceManager.GetString("BillCashes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إلغاء.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تغيير تسلسل الصكوك.
        /// </summary>
        public static string ChangeSequence {
            get {
                return ResourceManager.GetString("ChangeSequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مربع تحديد.
        /// </summary>
        public static string CheckBox {
            get {
                return ResourceManager.GetString("CheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إقفال.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to القيود غير المرحلة من الصرف والقبض.
        /// </summary>
        public static string ClosedDocuments {
            get {
                return ResourceManager.GetString("ClosedDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إغلاق السنة.
        /// </summary>
        public static string CloseYear {
            get {
                return ResourceManager.GetString("CloseYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مراكز التكلفة.
        /// </summary>
        public static string CostCenters {
            get {
                return ResourceManager.GetString("CostCenters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إضافة.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تكوين قيد إهلاك.
        /// </summary>
        public static string CreateDepreciationEntry {
            get {
                return ResourceManager.GetString("CreateDepreciationEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الترحيل.
        /// </summary>
        public static string Deport {
            get {
                return ResourceManager.GetString("Deport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to القيود المرحلة.
        /// </summary>
        public static string DeportedEntries {
            get {
                return ResourceManager.GetString("DeportedEntries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قائمة منسدلة.
        /// </summary>
        public static string DropDownList {
            get {
                return ResourceManager.GetString("DropDownList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعديل.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعديل التاريخ.
        /// </summary>
        public static string EditDate {
            get {
                return ResourceManager.GetString("EditDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعديل السنة.
        /// </summary>
        public static string EditYear {
            get {
                return ResourceManager.GetString("EditYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to القيود.
        /// </summary>
        public static string Entries {
            get {
                return ResourceManager.GetString("Entries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to القيود غير المرحلة الخارجية.
        /// </summary>
        public static string ExternalEntry {
            get {
                return ResourceManager.GetString("ExternalEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إدخال رقم يدوياً.
        /// </summary>
        public static string InsertNumber {
            get {
                return ResourceManager.GetString("InsertNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حقل رقمي.
        /// </summary>
        public static string Numeric {
            get {
                return ResourceManager.GetString("Numeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زر اختيار.
        /// </summary>
        public static string RadioButton {
            get {
                return ResourceManager.GetString("RadioButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سندات القبض بالصكوك.
        /// </summary>
        public static string ReceiptBonds {
            get {
                return ResourceManager.GetString("ReceiptBonds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سندات القبض النقدية.
        /// </summary>
        public static string ReceiptCashes {
            get {
                return ResourceManager.GetString("ReceiptCashes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إلغاء الإقفال.
        /// </summary>
        public static string Reopen {
            get {
                return ResourceManager.GetString("Reopen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إعادة فتح السنة.
        /// </summary>
        public static string ReopenYear {
            get {
                return ResourceManager.GetString("ReopenYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to استعادة.
        /// </summary>
        public static string Restore {
            get {
                return ResourceManager.GetString("Restore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حفظ وتعديل.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حقل نصي كبير.
        /// </summary>
        public static string TextArea {
            get {
                return ResourceManager.GetString("TextArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حقل نصي.
        /// </summary>
        public static string TextBox {
            get {
                return ResourceManager.GetString("TextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to القيود الغير مرحلة.
        /// </summary>
        public static string UnDeportedEntries {
            get {
                return ResourceManager.GetString("UnDeportedEntries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صلاحيات المستخدمين.
        /// </summary>
        public static string UserGroups {
            get {
                return ResourceManager.GetString("UserGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المستخدمين.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مشاهدة.
        /// </summary>
        public static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
    }
}
