#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Almotkaml.HR.Others.linqq
{
    using System.Data.Linq;
    using System.Data.Linq.Mapping;
    using System.Reflection;


    [global::System.Data.Linq.Mapping.DatabaseAttribute(Name = "AlmotkamlHr")]
    public partial class DataClasses1DataContext : System.Data.Linq.DataContext
    {

        private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();

        #region Extensibility Method Definitions
        partial void OnCreated();
        #endregion


        public DataClasses1DataContext(string connection) :
                base(connection, mappingSource)
        {
            OnCreated();
        }

        public DataClasses1DataContext(System.Data.IDbConnection connection) :
                base(connection, mappingSource)
        {
            OnCreated();
        }

        public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) :
                base(connection, mappingSource)
        {
            OnCreated();
        }

        public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) :
                base(connection, mappingSource)
        {
            OnCreated();
        }

        [global::System.Data.Linq.Mapping.FunctionAttribute(Name = "dbo.serch_reprt_withe_division1")]
        public ISingleResult<serch_reprt_withe_division1Result> serch_reprt_withe_division1([global::System.Data.Linq.Mapping.ParameterAttribute(Name = "DivisionId", DbType = "Int")] System.Nullable<int> divisionId, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType = "Int")] System.Nullable<int> employeeType)
        {
            IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), divisionId, employeeType);
            return ((ISingleResult<serch_reprt_withe_division1Result>)(result.ReturnValue));
        }
    }

    public partial class serch_reprt_withe_division1Result
    {

        private string _FirstName;

        private int _EmployeeId;

        private string _MonyeNumber;

        private System.Nullable<decimal> _Sanction;

        private System.Nullable<decimal> _ExtraGeneralValue;

        private System.Nullable<decimal> _BasicSalary;

        private System.Nullable<decimal> _Extrawork;

        private System.Nullable<decimal> _ExtraWorkHoures;

        private System.Nullable<decimal> _ExtraWorkVacationHoures;

        private System.Nullable<decimal> _WithoutPay;

        private System.Nullable<decimal> _SituationOnNet;

        private System.Nullable<decimal> _SituationOnTotal;

        private System.Nullable<decimal> _SubjectSalary;

        private System.Nullable<decimal> _TotalSalary;

        private System.Nullable<decimal> _SolidarityFund;

        private System.Nullable<decimal> _NetSalary;

        private System.Nullable<decimal> _PrepaidPremium;

        private System.Nullable<decimal> _EmployeeShare;

        private System.Nullable<decimal> _ExemptionTax;

        private System.Nullable<decimal> _IncomeTax;

        private System.Nullable<decimal> _JihadTax;

        private System.Nullable<decimal> _FinalySalary;

        private System.Nullable<decimal> _StampTax;

        private System.Nullable<decimal> _AdvancePremiumInside;

        private System.Nullable<decimal> _AdvancePremiumOutside;

        private System.Nullable<decimal> _AbsenceDays;

        private string _JobNumber;

        private System.Nullable<int> _EmployeeStat;

        private string _Name;

        private string _NationalNumber;

        private System.Nullable<decimal> _CompanyShare;

        private System.Nullable<decimal> _ExtraValue;

        private System.Nullable<decimal> _SickVaction;

        public serch_reprt_withe_division1Result()
        {
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_FirstName", DbType = "NVarChar(128) NOT NULL", CanBeNull = false)]
        public string FirstName
        {
            get
            {
                return this._FirstName;
            }
            set
            {
                if ((this._FirstName != value))
                {
                    this._FirstName = value;
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_EmployeeId", DbType = "Int NOT NULL")]
        public int EmployeeId
        {
            get
            {
                return this._EmployeeId;
            }
            set
            {
                if ((this._EmployeeId != value))
                {
                    this._EmployeeId = value;
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_MonyeNumber", DbType = "NVarChar(MAX)")]
        public string MonyeNumber
        {
            get
            {
                return this._MonyeNumber;
            }
            set
            {
                if ((this._MonyeNumber != value))
                {
                    this._MonyeNumber = value;
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_Sanction", DbType = "Decimal(18,2)")]
        public System.Nullable<decimal> Sanction
        {
            get
            {
                return this._Sanction;
            }
            set
            {
                if ((this._Sanction != value))
                {
                    this._Sanction = value;
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_ExtraGeneralValue", DbType = "Decimal(18,2)")]
        public System.Nullable<decimal> ExtraGeneralValue
        {
            get
            {
                return this._ExtraGeneralValue;
            }
            set
            {
                if ((this._ExtraGeneralValue != value))
                {
                    this._ExtraGeneralValue = value;
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_BasicSalary", DbType = "Decimal(18,2)")]
        public System.Nullable<decimal> BasicSalary
        {
            get
            {
                return this._BasicSalary;
            }
            set
            {
                if ((this._BasicSalary != value))
                {
                    this._BasicSalary = value;
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_Extrawork", DbType = "NVarChar(MAX)")]
        public System.Nullable<decimal> Extrawork
        {
            get
            {
                return this._Extrawork;
            }
            set
            {
                if ((this._Extrawork != value))
                {
                    this._Extrawork = value;
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_ExtraWorkHoures", DbType = "Decimal(18,2)")]
        public System.Nullable<decimal> ExtraWorkHoures
        {
            get
            {
                return this._ExtraWorkHoures;
            }
            set
            {
                if ((this._ExtraWorkHoures != value))
                {
                    this._ExtraWorkHoures = value;
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_ExtraWorkVacationHoures", DbType = "Decimal(18,2)")]
        public System.Nullable<decimal> ExtraWorkVacationHoures
        {
            get
            {
                return this._ExtraWorkVacationHoures;
            }
            set
            {
                if ((this._ExtraWorkVacationHoures != value))
                {
                    this._ExtraWorkVacationHoures = value;
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_WithoutPay", DbType = "Decimal(18,2)")]
        public System.Nullable<decimal> WithoutPay
        {
            get
            {
                return this._WithoutPay;
            }
            set
            {
                if ((this._WithoutPay != value))
                {
                    this._WithoutPay = value;
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_SituationOnNet", DbType = "NVarChar(MAX)")]
        public System.Nullable<decimal> SituationOnNet
        {
            get
            {
                return this._SituationOnNet;
            }
            set
            {
                if ((this._SituationOnNet != value))
                {
                    this._SituationOnNet = value;
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_SituationOnTotal", DbType = "NVarChar(MAX)")]
        public System.Nullable<decimal> SituationOnTotal
        {
            get
            {
                return this._SituationOnTotal;
            }
            set
            {
                if ((this._SituationOnTotal != value))
                {
                    this._SituationOnTotal = value;
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_SubjectSalary", DbType = "NVarChar(MAX)")]
        public System.Nullable<decimal> SubjectSalary
        {
            get
            {
                return this._SubjectSalary;
            }
            set
            {
                if ((this._SubjectSalary != value))
                {
                    this._SubjectSalary = value;
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_TotalSalary", DbType = "NVarChar(MAX)")]
        public System.Nullable<decimal> TotalSalary
        {
            get
            {
                return this._TotalSalary;
            }
            set
            {
                if ((this._TotalSalary != value))
                {
                    this._TotalSalary = value;
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_SolidarityFund", DbType = "NVarChar(MAX)")]
        public System.Nullable<decimal> SolidarityFund
        {
            get
            {
                return this._SolidarityFund;
            }
            set
            {
                if ((this._SolidarityFund != value))
                {
                    this._SolidarityFund = value;
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_NetSalary", DbType = "NVarChar(MAX)")]
        public System.Nullable<decimal> NetSalary
        {
            get
            {
                return this._NetSalary;
            }
            set
            {
                if ((this._NetSalary != value))
                {
                    this._NetSalary = value;
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_PrepaidPremium", DbType = "NVarChar(MAX)")]
        public System.Nullable<decimal> PrepaidPremium
        {
            get
            {
                return this._PrepaidPremium;
            }
            set
            {
                if ((this._PrepaidPremium != value))
                {
                    this._PrepaidPremium = value;
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_EmployeeShare", DbType = "NVarChar(MAX)")]
        public System.Nullable<decimal> EmployeeShare
        {
            get
            {
                return this._EmployeeShare;
            }
            set
            {
                if ((this._EmployeeShare != value))
                {
                    this._EmployeeShare = value;
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_ExemptionTax", DbType = "NVarChar(MAX)")]
        public System.Nullable<decimal> ExemptionTax
        {
            get
            {
                return this._ExemptionTax;
            }
            set
            {
                if ((this._ExemptionTax != value))
                {
                    this._ExemptionTax = value;
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_IncomeTax", DbType = "NVarChar(MAX)")]
        public System.Nullable<decimal> IncomeTax
        {
            get
            {
                return this._IncomeTax;
            }
            set
            {
                if ((this._IncomeTax != value))
                {
                    this._IncomeTax = value;
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_JihadTax", DbType = "NVarChar(MAX)")]
        public System.Nullable<decimal> JihadTax
        {
            get
            {
                return this._JihadTax;
            }
            set
            {
                if ((this._JihadTax != value))
                {
                    this._JihadTax = value;
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_FinalySalary", DbType = "NVarChar(MAX)")]
        public System.Nullable<decimal> FinalySalary
        {
            get
            {
                return this._FinalySalary;
            }
            set
            {
                if ((this._FinalySalary != value))
                {
                    this._FinalySalary = value;
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_StampTax", DbType = "NVarChar(MAX)")]
        public System.Nullable<decimal> StampTax
        {
            get
            {
                return this._StampTax;
            }
            set
            {
                if ((this._StampTax != value))
                {
                    this._StampTax = value;
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_AdvancePremiumInside", DbType = "Decimal(18,2)")]
        public System.Nullable<decimal> AdvancePremiumInside
        {
            get
            {
                return this._AdvancePremiumInside;
            }
            set
            {
                if ((this._AdvancePremiumInside != value))
                {
                    this._AdvancePremiumInside = value;
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_AdvancePremiumOutside", DbType = "Decimal(18,2)")]
        public System.Nullable<decimal> AdvancePremiumOutside
        {
            get
            {
                return this._AdvancePremiumOutside;
            }
            set
            {
                if ((this._AdvancePremiumOutside != value))
                {
                    this._AdvancePremiumOutside = value;
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_AbsenceDays", DbType = "Int")]
        public System.Nullable<decimal> AbsenceDays
        {
            get
            {
                return this._AbsenceDays;
            }
            set
            {
                if ((this._AbsenceDays != value))
                {
                    this._AbsenceDays = value;
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_JobNumber", DbType = "Int")]
        public string JobNumber
        {
            get
            {
                return this._JobNumber;
            }
            set
            {
                if ((this._JobNumber != value))
                {
                    this._JobNumber = value;
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_EmployeeStat", DbType = "Int")]
        public System.Nullable<int> EmployeeStat
        {
            get
            {
                return this._EmployeeStat;
            }
            set
            {
                if ((this._EmployeeStat != value))
                {
                    this._EmployeeStat = value;
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_Name", DbType = "NVarChar(MAX)")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                if ((this._Name != value))
                {
                    this._Name = value;
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_NationalNumber", DbType = "NVarChar(MAX)")]
        public string NationalNumber
        {
            get
            {
                return this._NationalNumber;
            }
            set
            {
                if ((this._NationalNumber != value))
                {
                    this._NationalNumber = value;
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_CompanyShare", DbType = "NVarChar(MAX)")]
        public System.Nullable<decimal> CompanyShare
        {
            get
            {
                return this._CompanyShare;
            }
            set
            {
                if ((this._CompanyShare != value))
                {
                    this._CompanyShare = value;
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_ExtraValue", DbType = "Decimal(18,2)")]
        public System.Nullable<decimal> ExtraValue
        {
            get
            {
                return this._ExtraValue;
            }
            set
            {
                if ((this._ExtraValue != value))
                {
                    this._ExtraValue = value;
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_SickVaction", DbType = "NVarChar(MAX)")]
        public System.Nullable<decimal> SickVaction
        {
            get
            {
                return this._SickVaction;
            }
            set
            {
                if ((this._SickVaction != value))
                {
                    this._SickVaction = value;
                }
            }
        }
    }
}
#pragma warning restore 1591
